# This is a basic workflow to help you get started with Actions

name: compile

# Controls when the workflow will run
on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: compile
      run: tsc src/index.ts
    - name: github pages upload
      run: |
        git config --global user.name 'litten2up'
        git config --global user.email 'litten2up@users.noreply.github.com'
        mv src/*.js built/
        git add built/index.js
        git commit -am "push to gh-pages"
        git push https://github.com/litten2up/typescript-website gh-pages
    
